POST http://localhost:45200/targets HTTP/1.1
content-type: application/json

{
    "base": ["好き", "だ", "食べ物", "は", "何", "です", "か", "?"], 
    "targets": [
        {
            "id": 1, 
            "sent": ["好き", "な", "色", "は", "何", "?"]
        },
        {
            "id": 2, 
            "sent": ["空", "な", "の", "色", "は", "何", "色", "?"]
        },
        {
            "id": 3,
            "sent": ["好き", "だ", "食べ物", "は", "何", "です", "か"]
        }
    ]
}