services:
  pymagnitude:
    container_name: pymagnitude
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workdir
    working_dir: /workdir
    ports:
      - 45200:45200